services:
   db:
      container_name: db
      image: postgres:17.0
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         PGDATA: /var/lib/postgresql/data/pgdata
      restart: always 
      volumes:
         - ./timemanager_pdgdata:/var/lib/postgresql/data
      # ports:
         # - '5432:5432' comment it out for security measures/ the containers are on the same network so they can communicate without exposing the port
      networks:
         - timemanager-network

   phoenix:
      container_name: phoenix
      build:
         context: ./backend 
      # ports:
      #    - '4000:4000'
      depends_on:
         - db
      networks:
         - timemanager-network
    
   frontend:
      container_name: frontend
      build:
         context: ./frontend
      # ports:
      #    - '8080:8080'
      depends_on:
         - phoenix
      networks:
         - timemanager-network

   nginx:
      container_name: nginx
      image: nginx:1.19.0
      ports:
         - '80:80'
      volumes:
         - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
         - frontend
      networks:
         - timemanager-network





volumes:
   timemanager_pdgdata:

networks:
   timemanager-network:
      driver: bridge
